WHITELIST = ["MSFT","NVDA","AAPL","AMZN","GOOGL","GOOG","META","AVGO","TSLA","JPM",
    "WMT","LLY","V","MA","NFLX","XOM","ORCL","COST","JNJ","HD",
    "PG","BAC","ABBV","KO","PLTR","CVX","TMUS","CRM","AMD","QCOM"]
BLACKLIST = ['LOW_IV_TICKERS']
MAX_TICKERS_PER_RUN = 30
SLEEP_BETWEEN_TICKERS = 1.5
OPTION_CACHE_MINUTES = 15
DATA_DIR = 'data'
ALERT_SCORE_MIN = 3
